export default {
  login: "Hacker-KM",
  id: 122519511,
  node_id: "U_kgDOB01_1w",
  avatar_url: "https://avatars.githubusercontent.com/u/122519511?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Hacker-KM",
  html_url: "https://github.com/Hacker-KM",
  followers_url: "https://api.github.com/users/Hacker-KM/followers",
  following_url:
    "https://api.github.com/users/Hacker-KM/following{/other_user}",
  gists_url: "https://api.github.com/users/Hacker-KM/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Hacker-KM/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Hacker-KM/subscriptions",
  organizations_url: "https://api.github.com/users/Hacker-KM/orgs",
  repos_url: "https://api.github.com/users/Hacker-KM/repos",
  events_url: "https://api.github.com/users/Hacker-KM/events{/privacy}",
  received_events_url: "https://api.github.com/users/Hacker-KM/received_events",
  type: "User",
  site_admin: false,
  name: "Kartik Mishra",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 30,
  public_gists: 0,
  followers: 2,
  following: 1,
  created_at: "2023-01-12T08:17:22Z",
  updated_at: "2023-10-18T10:01:19Z",
};
