export default [
  {
    "login": "akash-singh8",
    "id": 85285176,
    "node_id": "MDQ6VXNlcjg1Mjg1MTc2",
    "avatar_url": "https://avatars.githubusercontent.com/u/85285176?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/akash-singh8",
    "html_url": "https://github.com/akash-singh8",
    "followers_url": "https://api.github.com/users/akash-singh8/followers",
    "following_url": "https://api.github.com/users/akash-singh8/following{/other_user}",
    "gists_url": "https://api.github.com/users/akash-singh8/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/akash-singh8/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/akash-singh8/subscriptions",
    "organizations_url": "https://api.github.com/users/akash-singh8/orgs",
    "repos_url": "https://api.github.com/users/akash-singh8/repos",
    "events_url": "https://api.github.com/users/akash-singh8/events{/privacy}",
    "received_events_url": "https://api.github.com/users/akash-singh8/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "achiever-21",
    "id": 132044694,
    "node_id": "U_kgDOB97Xlg",
    "avatar_url": "https://avatars.githubusercontent.com/u/132044694?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/achiever-21",
    "html_url": "https://github.com/achiever-21",
    "followers_url": "https://api.github.com/users/achiever-21/followers",
    "following_url": "https://api.github.com/users/achiever-21/following{/other_user}",
    "gists_url": "https://api.github.com/users/achiever-21/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/achiever-21/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/achiever-21/subscriptions",
    "organizations_url": "https://api.github.com/users/achiever-21/orgs",
    "repos_url": "https://api.github.com/users/achiever-21/repos",
    "events_url": "https://api.github.com/users/achiever-21/events{/privacy}",
    "received_events_url": "https://api.github.com/users/achiever-21/received_events",
    "type": "User",
    "site_admin": false
  }
]